name: AWS Lambda Deploy 
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: decode secrets Base64
        uses: akiojin/decode-base64-github-action@v0.1.0
        with:
            base64: ${{ secrets.SETTINGS_JSON }}
            output-path: ./src/main/resources/application-prod.yml

      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: get-caller-identity is allowed to run on role.
        run: aws sts get-caller-identity

      - name: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -DskipTests=true --file pom.xml

      - name: lambda update
        run: |
          cd target
          aws lambda update-function-code --function-name ${{ secrets.FUNCTION_NAME }} --zip-file fileb://${{ secrets.FUNCTION_NAME }}-lambda-package.zip --publish
